# GitHub Pages Configuration for Time Series Analysis Dashboard
# This file configures Jekyll for optimal GitHub Pages deployment

# Site settings
title: "Upside Time Series Analysis"
description: "Advanced business intelligence dashboard for restaurant sales forecasting and strategic decision making"
author: "Allen"
email: "your-email@example.com"
url: "https://kayfay.github.io/upside-timeseries"
baseurl: "/upside-timeseries"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  reports:
    output: true
    permalink: /reports/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "reports"
    values:
      layout: "report"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - *.R
  - *.rds
  - *.xlsx
  - *.Rproj

# Include files that should be processed
include:
  - _config.yml
  - index.html
  - *.png
  - *.md
  - *.css
  - *.js

# Theme settings (if using a theme)
# theme: minima

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# SEO settings
lang: en_US
locale: en_US

# Social media
twitter:
  username: your-twitter-handle
  card: summary_large_image

# Analytics (optional)
google_analytics: # UA-XXXXXXXXX-X

# Comments (optional)
disqus:
  shortname: your-disqus-shortname

# Search
search: true

# Sitemap
sitemap:
  exclude: ['/feed.xml', '/robots.txt']
  change_frequency: weekly
  priority: 0.8

# Robots.txt
robots:
  user_agent: '*'
  disallow:
    - /admin/
    - /private/
  sitemap: https://kayfay.github.io/upside-timeseries/sitemap.xml

# Security headers
security_headers:
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin

# Performance optimization
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []
  startings: [html, head, body]

# Cache settings
cache:
  enabled: true
  cache_dir: .jekyll-cache
  cache_control:
    default: "public, max-age=31536000"
    images: "public, max-age=31536000"
    css: "public, max-age=31536000"
    js: "public, max-age=31536000"
